excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://cauerego.github.io
title: cregox
email: caue@cregox.com
author: Caue Rego
description: Church of Tech B.A.S.I.U.X.'s quest to The Singularity
paginate: 6
google_analytics: UA-4687862-13
