excerpt_separator: ""
highlighter: true
markdown: kramdown
url: https://blog.cregox.com
title: cregox blog
email: caue@cregox.com
author: Caue Rego
description: B.A.S.I.U.X. - a quest to The Tech Singularity
paginate: 6
google_analytics: UA-4687862-13
