excerpt_separator: ""
highlighter: rouge # no idea why, but https://sacha.me/articles/jekyll-rouge/
markdown: kramdown
url: https://blog.cregox.com
title: cregox experimental blog
email: caue@cregox.com
author: Caue Rego
description: blogging, experimenting with jekyll and trying to write a bdd novel
google_analytics: UA-4687862-13
permalink: /:categories/:title-:year:month:day #-:hash  <-- fallback, while I can find no way to use this "hash" in the plugin
#gems:
#    - jekyll-hashpermalink
